### ISSUE TITLE
Дублирование интернета

### ISSUE THREAD

**Issue by Komzpa** [RudenkoPeter/KD#11]
Нужна land line для интернета. Приезжать в деревню нажать "reconnect" неприкольно.

Самая ближайшая из доступных независимых - телефон на доме 24.

**Comment by peter-hanzo** [comment]
Варианты:
1. протянуть телефонную линию от участка 24 под землей
2. Протянуть сетевой кабель или Wi-fi от дома №24 (позволит объединить два участка в сеть)
3. Подать заявку на установку собственного телефонного номера на участке 57
4. Договорится с соседями о подключении к их интернету с оплатой

**Comment by Komzpa** [comment]
Wifi уже не достал. Во что станет нормальная проводная сеть?

**Comment by peter-hanzo** [comment]
Расстояние около 600м
1. Провести по столбам витую пару стоит 350-450$
2. Провести новый телефон на 57й участок будет стоит меньше 300$ но придется подождать, позже подробности узнаю
3. Вести телефонный кабель от 24го дома не вижу смысла т.к. цена будет 300-350$ по воздуху, а под землей еще дороже

**Comment by Komzpa** [comment]
ты учитываешь максимальную длину сегмента витой пары? 100..300м в зависимости от многих параметров оборудования и стандарта :)

**Comment by peter-hanzo** [comment]
Нет, этого не учел. Тогда вижу только один вариант - провести нормальный телефон на участок 57

**Comment by peter-hanzo** [comment]
Узнал подробности в Червенском сервис центре Белтелеком. 
1. Новый телефонный номер провести на участок 57 нет возможности т.к. в деревне Ялча нет свободных линий (если только кто-то отключит свой телефон за ненадобностью)
2. Продублировать номер из дома 24 тоже не получиться. 
3. Остается вариант переноса номера с участка 24 на участок 57, но для выяснения этой возможности надо пригласить специалистов Белтелеком. Специалисты могут приехать в начале лета и посмотреть есть ли возможность переноса с одного дома на другой. Телефонные кабеля в Ялче проложены под землей.

**Comment by Komzpa** [comment]
нужен интернет. есть ли опции подключения интернета без телефонной линии? (точно умеют выдавать ethernet-модем с антенной и особой симкой)

**Comment by peter-hanzo** [comment]
Белтелеком кроме проводного интернета предлагает доступ к интернету через 2G и 3G. У него договор с МТС на облуживание их сети, поэтому это будет тоже самое, что купить симку МТС и поставить в 3G модем. Путь 3G насколько я понял нам не подходит из-за плохого покрытия и связи

**Comment by Komzpa** [comment]
интернет считаем задублированным.
