### ISSUE TITLE
переписать описание в корне проекта

### ISSUE THREAD

**Issue by Komzpa** [RudenkoPeter/KD#2]
Слова "самостоятельно" и "$1000 ежемесячно" - это не про этот проект :)

**Comment by peter-hanzo** [comment]
согласен, уже не про этот)

**Comment by peter-hanzo** [comment]
Так норм? "Каждый год комфортно проживать в период весна-осень"

**Comment by Komzpa** [comment]
у этого дома уже зафиксирована площадь, этажность и другие параметры. можно писать их, а не требования двухгодичной давности :)

**Comment by peter-hanzo** [comment]
Может убрать "требования" и написать паспорт объекта?

**Comment by Komzpa** [comment]
похоже на то.
