### ISSUE TITLE
Серверная

### ISSUE THREAD

**Issue by Komzpa** [RudenkoPeter/KD#5]
В доме нет серверной.

Серверная должна:
 - быть сухой;
 - кондиционироваться (держать +5..+30 вне зависимости);
 - соединяться по Ethernet c остальным домом;
 - быть шумосветоизолированной от спального места;
 - иметь ИБП;
 - иметь интернет.

**Comment by peter-hanzo** [comment]
Надо определить точное и постоянное место под серверную. Варианты: там где сейчас или рядом с электрощитком.

**Comment by Komzpa** [comment]
Как это может выглядеть, если рядом с электрощитком? :)

Была ещё мысль о тёплой коробке под домом.

**Comment by peter-hanzo** [comment]
Если делать что-то под домом, то и электрощиток туда же. Два шкафа независимых. Надо подумать про легкий доступ. А еще сервера закапывают под землю))

**Comment by peter-hanzo** [comment]
какие должны быть параметры у ИПБ?

**Comment by Komzpa** [comment]
ИПБ должен быть из списка совместимости с NUT, http://networkupstools.org/stable-hcl.html
Продаваться в розницу в Беларуси, мощность - наибольшая из доступных.

**Comment by peter-hanzo** [comment]
Хватит ли того ИПБ который сейчас есть?
Серверную решили сделать под полом рядом с крыльцом. Предлагаю сделать утепленный каркас и установить в него вот этот [ящик](http://regul.by/images/shitmonpan44.jpg). С одной стороны сделать электрику, со второго серверную. [Корпус](https://goo.gl/photos/XQETEbPoY8gZ1Rc56) металлический мм: 1600x600x400; цоколь, мм: 100x600x400. Масса: 55,4 кг

**Comment by Komzpa** [comment]
как закрывается ящик?
куда направлена дверь?
как реагирует на разлитую на него воду при такой установке - затеканием внутрь или сбрасыванием наружу?
можно ли будет его выломать смещением вбок?

**Comment by Komzpa** [comment]
бесперебойника должно хватить.
кроме того, хочется разводки, электрики, которая бы позволила легко выключить весь дом, но не серверную.

**Comment by peter-hanzo** [comment]
Ящик закрывается на два засова, так же можно повесить дополнительный замок
Дверь закрывается горизонтально, в закрытом состоянии параллельна плоскости пола
Чтобы избежать затекания выберу дверь с навесом наружу а не внутрь, также можно сделать небольшой уклон корпуса.
Смещение будет исключено если закрепить корпус анкерами к бетонному основанию
Обесточить весь дом исключая серверную можно. Для этого надо поставить два независимых вводных автомата, когда будем переделывать электрощиток.

**Comment by peter-hanzo** [comment]
**Планируется следующее:**
2.1	установка серверного шкафа
2.2	заливка основания под серверный шкаф
2.3	подключить дополнительные автоматы
2.4	подключить умное освещение
2.5	переустановить электроящик

Пункты (2.1) (2.2) взаимосвязаны и идут перед (2.3) (2.4) (2.5)
Пункты (2.3) (2.4) (2.5) делает один специалист, поэтому желательно их не разделять.
