### ISSUE TITLE
Погодные датчики

### ISSUE THREAD

**Issue by Komzpa** [RudenkoPeter/KD#9]
- скорость и направление ветра - на шапочке;
 - давление.

**Comment by peter-hanzo** [comment]
какие требования к выходным данным? через какой интерфейс их снимать в реальном времени?

**Comment by Komzpa** [comment]
Требования от проекта OpenWeatherMap:

http://openweathermap.org/stations-30

комментарий разработчика:
"Нам интереснее всего - температура, давление, влажность и осадки ￼ Это то, что напрямую может участвовать в метеомодели и уточнять погодные данные по региону"

**Comment by peter-hanzo** [comment]
тогда нужна полноценная домашняя метеостанция: 
http://www.advant-mpi.by/meteostancii.php
http://minsk.deal.by/p25301012-meteostantsiya-davis-vantage.html

**Comment by Komzpa** [comment]
есть такое:

http://www.ebay.com/itm/La-Crosse-Technology-Wind-Speed-Weather-Station-327-1414W-/391463045904?hash=item5b25040b10:g:WusAAOSwQjZXQG~G

**Comment by peter-hanzo** [comment]
Он меряет только: скорость ветра, температуру, влажность. Нет ни давления, ни осадков. А ветер насколько я понял OpenWeatherMap не сильно интересен. Плюс в нем один - это полноценный внешний датчик с рабочим диапазоном -40+60

**Comment by peter-hanzo** [comment]
Пока нашел только профессиональные: http://www.meteomaster.ru/products/catalog/osnovnye-meteostantsii-DAVIS/
Ищу китайские аналоги

**Comment by peter-hanzo** [comment]
Вот бюджетные варианты:
http://www.ambientweather.com/amws2080.html

https://www.amazon.com/gp/product/B01HH4WZXG/ref=s9_acsd_zwish_hd_bw_bQtb07_c_x_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-11&pf_rd_r=1W8F8Q4PH4JK31Z2JDPJ&pf_rd_t=101&pf_rd_p=41723d1e-c876-595b-ac04-8c3e8e195c68&pf_rd_i=397435011

http://www.ebay.com/itm/Ambient-Weather-Wireless-Remote-Monitoring-Weather-Station-/252714338503?hash=item3ad6f2c8c7:g:rsUAAOSwnHZYcV1p

**Comment by peter-hanzo** [comment]
Я бы рассмотрел вот на такой вариант хоть он и дороже:
http://www.ebay.com/itm/Davis-Instruments-Vantage-Vue-Wireless-Integrated-Rugged-Sensor-Sensor-Suite-New/381664572317?_trksid=p2047675.c100005.m1851&_trkparms=aid%3D2220071%26algo%3DSIC.MBE%26ao%3D2%26asc%3D20131003132420%26meid%3D68260c85159949cda59d3e3c86993674%26pid%3D100005%26rk%3D6%26rkt%3D6%26sd%3D142180728902
